# Generated by Django 6.0.5 on 2026-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hajjservice_pilgrims_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilgrimprofile',
            old_name='passport_number',
            new_name='identity_number',
        ),
        migrations.AddField(
            model_name='pilgrimprofile',
            name='identity_type',
            field=models.CharField(choices=[('National', 'National ID'), ('Passport', 'Passport')], default='National', max_length=10),
        ),
    ]
