# Generated by Django 6.0.5 on 2026-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_passport_number_pilgrimprofile_identity_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
